#!/usr/bin/env bash
#
# Run the CLI<->server integration tests: start the server jar, drive it with the built ngb-cli
# through every row of e2e/cli/testcases.csv, stop it again.
#
# Assumes NGB and the CLI are already built and in ../dist/ - `./gradlew buildJar buildCli`, or
# `make jar cli-build` in .devenv/. Run it from the repository root:
#
#   bash e2e/integration_tests.sh
#
# Environment:
#   NGB_E2E_JAR       server jar to run                  (default dist/catgenome.jar)
#   NGB_E2E_RUN_DIR   database, file cache and log go here, and are deleted at the end
#                                                        (default /tmp/ngb-cli-e2e)
#   NGB_E2E_PORT      port the server listens on          (default 8080; testcases.csv has
#                                                         localhost:8080 written into three rows,
#                                                         so this is not really adjustable)
#   KEEP_TEST_DATA    set to keep e2e/cli/test_data/ afterwards
#
# The fixtures are generated by e2e/cli/prepare_test_data.sh from the server module's test
# resources. They used to be wget'd from http://ngb.opensource.epam.com/, which no longer resolves.

set -uo pipefail

TEST_DATA_PATH="$(pwd)/e2e/cli/test_data"
TEST_DATA_RELATIVE_PATH="e2e/cli/test_data"
DIST_PATH="$(pwd)/dist"
JAR_PATH="${NGB_E2E_JAR:-${DIST_PATH}/catgenome.jar}"
CLI_PATH="${DIST_PATH}/ngb-cli.tar.gz"
CLI_BIN_PATH="${DIST_PATH}/ngb-cli/bin/ngb"
TEST_CASES_PATH="$(pwd)/e2e/cli/testcases.csv"
RUN_DIR="${NGB_E2E_RUN_DIR:-/tmp/ngb-cli-e2e}"
PORT="${NGB_E2E_PORT:-8080}"
SERVER_URL="http://localhost:${PORT}/catgenome"

for f in "$JAR_PATH" "$CLI_PATH"; do
    [ -f "$f" ] && continue
    echo "missing $f - build it first (./gradlew buildJar buildCli)" >&2
    exit 1
done

# Generate the test data
bash e2e/cli/prepare_test_data.sh "$TEST_DATA_PATH" || exit 1

# Unpack CLI distribution
rm -rf "${DIST_PATH}/ngb-cli"
tar -zxf "$CLI_PATH" -C "$DIST_PATH" || exit 1

# Run NGB server. Its database and file cache go under $RUN_DIR rather than into the working
# directory, which is the repository root: the "register by relative path" rows resolve their
# paths against the server's working directory, so that cannot be moved. --enable-native-access
# silences Lucene's foreign-memory warnings, as in every other launcher NGB ships.
#
# ngs.data.root.path has to be set, and to something other than "/", or every row that registers a
# file by path is refused with "Server file system browsing is not allowed": UrlValidatorService
# treats a root of "/" as "browsing disabled" regardless of file.browsing.allowed, which the `jar`
# profile's packaged catgenome.properties already sets to true. It goes in a properties file rather
# than on the command line because both values are read as `#{catgenome['...']}` - SpEL over the
# PropertiesFactoryBean of AppConfiguration's @PropertySource list, not over the environment - so
# --ngs.data.root.path=... would be silently ignored. --conf names the directory to read it from.
SERVER_PID=""
cleanup() {
    [ -n "$SERVER_PID" ] && kill "$SERVER_PID" 2>/dev/null && wait "$SERVER_PID" 2>/dev/null
    [ -n "${KEEP_TEST_DATA:-}" ] || rm -rf "$TEST_DATA_PATH"
    rm -rf "$RUN_DIR"
}
trap cleanup EXIT

rm -rf "$RUN_DIR"
mkdir -p "$RUN_DIR/contents" "$RUN_DIR/H2" "$RUN_DIR/config" || exit 1
{
    echo "file.browsing.allowed=true"
    echo "ngs.data.root.path=$(pwd)"
} > "${RUN_DIR}/config/catgenome.properties"

java --enable-native-access=ALL-UNNAMED -jar "${JAR_PATH}" \
    --server.port="${PORT}" \
    --conf="${RUN_DIR}/config" \
    --files.base.directory.path="${RUN_DIR}/contents" \
    --database.jdbc.url="jdbc:h2:file:${RUN_DIR}/H2/catgenome" \
    > "${RUN_DIR}/server.log" 2>&1 &
SERVER_PID=$!

printf 'Waiting for NGB to start'
for _ in $(seq 1 90); do
    if curl -fsS -o /dev/null "${SERVER_URL}/restapi/version"; then
        echo " up"
        break
    fi
    if ! kill -0 "$SERVER_PID" 2>/dev/null; then
        echo " the server exited; last 40 lines of ${RUN_DIR}/server.log:"
        tail -40 "${RUN_DIR}/server.log"
        exit 1
    fi
    printf '.'
    sleep 2
done

if ! curl -fsS -o /dev/null "${SERVER_URL}/restapi/version"; then
    echo " gave up waiting; last 40 lines of ${RUN_DIR}/server.log:"
    tail -40 "${RUN_DIR}/server.log"
    exit 1
fi

# Run tests
./gradlew integrationCliTest --no-daemon \
    -PcliPath="${CLI_BIN_PATH}" \
    -PresourcePath="${TEST_DATA_PATH}" \
    -PresourceRelativePath="${TEST_DATA_RELATIVE_PATH}" \
    -PtestCases="${TEST_CASES_PATH}"
