/*
 * MIT License
 *
 * Copyright (c) 2016 EPAM Systems
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) 
// Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.04 at 04:45:29 PM MSK 
//

package com.epam.catgenome.manager.externaldb.bindings.uniprot;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Describes the names for the protein and parts thereof. Equivalent to the flat
 * file DE-line.
 * 
 * <p>
 * Java class for proteinType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="proteinType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://uniprot.org/uniprot}proteinNameGroup"/>
 *         &lt;element name="domain" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{http://uniprot.org/uniprot}proteinNameGroup"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="component" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{http://uniprot.org/uniprot}proteinNameGroup"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "proteinType", propOrder = { "recommendedName", "alternativeName", "submittedName", "allergenName",
        "biotechName", "cdAntigenName", "innName", "domain", "component" })
public class ProteinType {

    protected ProteinType.RecommendedName recommendedName;
    protected List<ProteinType.AlternativeName> alternativeName;
    protected List<ProteinType.SubmittedName> submittedName;
    protected EvidencedStringType allergenName;
    protected EvidencedStringType biotechName;
    protected List<EvidencedStringType> cdAntigenName;
    protected List<EvidencedStringType> innName;
    protected List<ProteinType.Domain> domain;
    protected List<ProteinType.Component> component;

    public ProteinType.RecommendedName getRecommendedName() {
        return recommendedName;
    }

    public void setRecommendedName(ProteinType.RecommendedName value) {
        this.recommendedName = value;
    }

    public List<ProteinType.AlternativeName> getAlternativeName() {
        if (alternativeName == null) {
            alternativeName = new ArrayList<>();
        }
        return this.alternativeName;
    }

    public List<ProteinType.SubmittedName> getSubmittedName() {
        if (submittedName == null) {
            submittedName = new ArrayList<>();
        }
        return this.submittedName;
    }

    public EvidencedStringType getAllergenName() {
        return allergenName;
    }

    public void setAllergenName(EvidencedStringType value) {
        this.allergenName = value;
    }

    public EvidencedStringType getBiotechName() {
        return biotechName;
    }

    public void setBiotechName(EvidencedStringType value) {
        this.biotechName = value;
    }

    public List<EvidencedStringType> getCdAntigenName() {
        if (cdAntigenName == null) {
            cdAntigenName = new ArrayList<>();
        }
        return this.cdAntigenName;
    }

    public List<EvidencedStringType> getInnName() {
        if (innName == null) {
            innName = new ArrayList<>();
        }
        return this.innName;
    }

    public List<ProteinType.Domain> getDomain() {
        if (domain == null) {
            domain = new ArrayList<>();
        }
        return this.domain;
    }

    public List<ProteinType.Component> getComponent() {
        if (component == null) {
            component = new ArrayList<>();
        }
        return this.component;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "fullName", "shortName", "ecNumber" })
    public static class AlternativeName {

        protected EvidencedStringType fullName;
        protected List<EvidencedStringType> shortName;
        protected List<EvidencedStringType> ecNumber;

        public EvidencedStringType getFullName() {
            return fullName;
        }

        public void setFullName(EvidencedStringType value) {
            this.fullName = value;
        }

        public List<EvidencedStringType> getShortName() {
            if (shortName == null) {
                shortName = new ArrayList<>();
            }
            return this.shortName;
        }

        public List<EvidencedStringType> getEcNumber() {
            if (ecNumber == null) {
                ecNumber = new ArrayList<>();
            }
            return this.ecNumber;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{http://uniprot.org/uniprot}proteinNameGroup"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "recommendedName", "alternativeName", "submittedName", "allergenName",
            "biotechName", "cdAntigenName", "innName" })
    public static class Component {

        protected ProteinType.RecommendedName recommendedName;
        protected List<ProteinType.AlternativeName> alternativeName;
        protected List<ProteinType.SubmittedName> submittedName;
        protected EvidencedStringType allergenName;
        protected EvidencedStringType biotechName;
        protected List<EvidencedStringType> cdAntigenName;
        protected List<EvidencedStringType> innName;

        public ProteinType.RecommendedName getRecommendedName() {
            return recommendedName;
        }

        public void setRecommendedName(ProteinType.RecommendedName value) {
            this.recommendedName = value;
        }

        public List<ProteinType.AlternativeName> getAlternativeName() {
            if (alternativeName == null) {
                alternativeName = new ArrayList<>();
            }
            return this.alternativeName;
        }

        public List<ProteinType.SubmittedName> getSubmittedName() {
            if (submittedName == null) {
                submittedName = new ArrayList<>();
            }
            return this.submittedName;
        }

        public EvidencedStringType getAllergenName() {
            return allergenName;
        }

        public void setAllergenName(EvidencedStringType value) {
            this.allergenName = value;
        }

        public EvidencedStringType getBiotechName() {
            return biotechName;
        }

        public void setBiotechName(EvidencedStringType value) {
            this.biotechName = value;
        }

        public List<EvidencedStringType> getCdAntigenName() {
            if (cdAntigenName == null) {
                cdAntigenName = new ArrayList<>();
            }
            return this.cdAntigenName;
        }

        public List<EvidencedStringType> getInnName() {
            if (innName == null) {
                innName = new ArrayList<>();
            }
            return this.innName;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{http://uniprot.org/uniprot}proteinNameGroup"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "recommendedName", "alternativeName", "submittedName", "allergenName",
            "biotechName", "cdAntigenName", "innName" })
    public static class Domain {

        protected ProteinType.RecommendedName recommendedName;
        protected List<ProteinType.AlternativeName> alternativeName;
        protected List<ProteinType.SubmittedName> submittedName;
        protected EvidencedStringType allergenName;
        protected EvidencedStringType biotechName;
        protected List<EvidencedStringType> cdAntigenName;
        protected List<EvidencedStringType> innName;

        public ProteinType.RecommendedName getRecommendedName() {
            return recommendedName;
        }

        public void setRecommendedName(ProteinType.RecommendedName value) {
            this.recommendedName = value;
        }

        public List<ProteinType.AlternativeName> getAlternativeName() {
            if (alternativeName == null) {
                alternativeName = new ArrayList<>();
            }
            return this.alternativeName;
        }

        public List<ProteinType.SubmittedName> getSubmittedName() {
            if (submittedName == null) {
                submittedName = new ArrayList<>();
            }
            return this.submittedName;
        }

        public EvidencedStringType getAllergenName() {
            return allergenName;
        }

        public void setAllergenName(EvidencedStringType value) {
            this.allergenName = value;
        }

        public EvidencedStringType getBiotechName() {
            return biotechName;
        }

        public void setBiotechName(EvidencedStringType value) {
            this.biotechName = value;
        }

        public List<EvidencedStringType> getCdAntigenName() {
            if (cdAntigenName == null) {
                cdAntigenName = new ArrayList<>();
            }
            return this.cdAntigenName;
        }

        public List<EvidencedStringType> getInnName() {
            if (innName == null) {
                innName = new ArrayList<>();
            }
            return this.innName;
        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "fullName", "shortName", "ecNumber" })
    public static class RecommendedName {

        @XmlElement(required = true)
        protected EvidencedStringType fullName;
        protected List<EvidencedStringType> shortName;
        protected List<EvidencedStringType> ecNumber;

        public EvidencedStringType getFullName() {
            return fullName;
        }

        public void setFullName(EvidencedStringType value) {
            this.fullName = value;
        }

        public List<EvidencedStringType> getShortName() {
            if (shortName == null) {
                shortName = new ArrayList<>();
            }
            return this.shortName;
        }

        public List<EvidencedStringType> getEcNumber() {
            if (ecNumber == null) {
                ecNumber = new ArrayList<>();
            }
            return this.ecNumber;
        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "fullName", "ecNumber" })
    public static class SubmittedName {

        @XmlElement(required = true)
        protected EvidencedStringType fullName;
        protected List<EvidencedStringType> ecNumber;

        public EvidencedStringType getFullName() {
            return fullName;
        }

        public void setFullName(EvidencedStringType value) {
            this.fullName = value;
        }

        public List<EvidencedStringType> getEcNumber() {
            if (ecNumber == null) {
                ecNumber = new ArrayList<>();
            }
            return this.ecNumber;
        }

    }

}
