#!/bin/bash -e

# Source debconf library.
. /usr/share/debconf/confmodule

# PORT number prompt
while true; do
  db_input high port_request || true
  db_go

  # Check the answer.
  db_get port_request
  if ! [[ "$RET" =~ ^[0-9]+$ ]] || (( "$RET" < 1023 )) || (( "$RET" > 65535)); then
    db_input high invalid_port || true
    db_go
    continue
  else
    break
  fi
  db_stop
done



