-- drop column REFERRED_PROJECT_ID, bookmarks are now not bounded to projects
ALTER TABLE CATGENOME.BOOKMARK DROP COLUMN IF EXISTS REFERRED_PROJECT_ID;

-- add not null column created_by
ALTER TABLE CATGENOME.BOOKMARK ADD COLUMN created_by BIGINT;
ALTER TABLE CATGENOME.BOOKMARK ADD COLUMN CREATED_DATE TIMESTAMP;
UPDATE CATGENOME.BOOKMARK SET created_by = 42, created_date = now();
ALTER TABLE CATGENOME.BOOKMARK ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE CATGENOME.BOOKMARK ALTER COLUMN created_date SET NOT NULL;
CREATE INDEX CATGENOME.bookmark_created_by_idx ON CATGENOME.BOOKMARK(created_by);