CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_TARGET START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS CATGENOME.TARGET (
    TARGET_ID          BIGINT NOT NULL PRIMARY KEY,
    TARGET_NAME        VARCHAR NOT NULL,
    DISEASES           VARCHAR NOT NULL,
    PRODUCTS           VARCHAR NOT NULL
);
CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_TARGET_GENE START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS CATGENOME.TARGET_GENE (
    TARGET_GENE_ID   BIGINT NOT NULL PRIMARY KEY,
    TARGET_ID        BIGINT NOT NULL,
    GENE_ID          VARCHAR NOT NULL,
    GENE_NAME        VARCHAR NOT NULL,
    TAX_ID           BIGINT NOT NULL,
    SPECIES_NAME     VARCHAR NOT NULL,
    PRIORITY         BIGINT,
    CONSTRAINT target_gene_id_fkey FOREIGN KEY (TARGET_ID) REFERENCES CATGENOME.TARGET(TARGET_ID)
);
