CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_HEATMAP START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS CATGENOME.HEATMAP (
    HEATMAP_ID             BIGINT NOT NULL PRIMARY KEY,
    NAME                   VARCHAR NOT NULL,
    PRETTY_NAME            VARCHAR,
    PATH                   VARCHAR NOT NULL,
    ROW_TREE_PATH          VARCHAR,
    COLUMN_TREE_PATH       VARCHAR,
    CELL_ANNOTATION_PATH   VARCHAR,
    LABEL_ANNOTATION_PATH  VARCHAR,
    CELL_VALUE_TYPE        INTEGER NOT NULL,
    MAX_CELL_VALUE         DECIMAL,
    MIN_CELL_VALUE         DECIMAL,
    CELL_VALUES            BLOB,
    COLUMN_LABELS          BLOB,
    ROW_LABELS             BLOB,
    CONTENT                BLOB,
    CELL_ANNOTATION        BLOB,
    LABEL_ANNOTATION       BLOB,
    ROW_TREE               BLOB,
    COLUMN_TREE            BLOB
);
