ALTER TABLE CATGENOME.TASK ALTER COLUMN TITLE VARCHAR(500);
ALTER TABLE CATGENOME.TASK ALTER COLUMN STATUS_REASON VARCHAR;
ALTER TABLE CATGENOME.TASK ALTER COLUMN QUERY VARCHAR;
ALTER TABLE CATGENOME.TASK ALTER COLUMN DATABASE VARCHAR(500);
ALTER TABLE CATGENOME.TASK ALTER COLUMN OPTIONS VARCHAR;