CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_BLAST_DATABASE_ORGANISM START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS CATGENOME.BLAST_DATABASE_ORGANISM (
    DATABASE_ORGANISM_ID  BIGINT NOT NULL PRIMARY KEY,
    DATABASE_ID                 BIGINT NOT NULL,
    TAX_ID                      BIGINT NOT NULL,
    CONSTRAINT blast_database_id_fkey FOREIGN KEY (DATABASE_ID) REFERENCES CATGENOME.BLAST_DATABASE(DATABASE_ID)
);
