CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_PROJECT_NOTE START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS CATGENOME.PROJECT_NOTE (
    NOTE_ID        BIGINT NOT NULL PRIMARY KEY,
    PROJECT_ID     BIGINT NOT NULL,
    TITLE          VARCHAR NOT NULL,
    CONTENT        VARCHAR NOT NULL,
    CONSTRAINT project_id_fkey FOREIGN KEY (PROJECT_ID) REFERENCES CATGENOME.PROJECT (PROJECT_ID)
);
