CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_TARGET_IDENTIFICATION START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS CATGENOME.TARGET_IDENTIFICATION (
    ID                  BIGINT NOT NULL PRIMARY KEY,
    TARGET_ID           BIGINT NOT NULL,
    NAME                VARCHAR,
    CREATED_DATE        TIMESTAMP NOT NULL,
    OWNER               VARCHAR NOT NULL,
    GENES_OF_INTEREST   VARCHAR NOT NULL,
    TRANSLATIONAL_GENES VARCHAR NOT NULL,
    CONSTRAINT target_identification_id_fkey FOREIGN KEY (TARGET_ID) REFERENCES CATGENOME.TARGET(TARGET_ID)
);
