CREATE TABLE IF NOT EXISTS CATGENOME.METADATA (
    ENTITY_ID BIGINT NOT NULL,
    ENTITY_CLASS VARCHAR NOT NULL,
    DATA TEXT DEFAULT NULL,
    CONSTRAINT METADATA_UNIQUE UNIQUE (ENTITY_ID, ENTITY_CLASS)
);
