CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_HOMOLOG_GROUP_GENE START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS CATGENOME.HOMOLOG_GROUP_GENE (
    ID BIGINT NOT NULL PRIMARY KEY,
    GROUP_ID BIGINT NOT NULL,
    GENE_ID BIGINT NOT NULL,
    TAX_ID BIGINT NOT NULL
    CONSTRAINT group_id_fkey FOREIGN KEY (GROUP_ID) REFERENCES CATGENOME.HOMOLOG_GROUP(ID)
);
