CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_PATHWAY START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS CATGENOME.PATHWAY (
    PATHWAY_ID          BIGINT NOT NULL PRIMARY KEY,
    BIO_DATA_ITEM_ID    BIGINT NOT NULL,
    PATHWAY_DESC        VARCHAR,
    CONSTRAINT pw_biological_data_item_id_fkey FOREIGN KEY (BIO_DATA_ITEM_ID) REFERENCES CATGENOME.BIOLOGICAL_DATA_ITEM (BIO_DATA_ITEM_ID)
);
