CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_HOMOLOG_GENE_DESCRIPTION START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS CATGENOME.HOMOLOG_GENE_DESCRIPTION (
    ID BIGINT NOT NULL PRIMARY KEY,
    SYMBOL VARCHAR(500) NOT NULL,
    TITLE VARCHAR(500) NOT NULL,
    TAX_ID BIGINT NOT NULL
    PROT_GI BIGINT NOT NULL,
    PROT_ACC VARCHAR(500) NOT NULL,
    PROT_LEN BIGINT NOT NULL,
    NUC_GI BIGINT NOT NULL,
    NUC_ACC VARCHAR(500) NOT NULL,
    LOCUS_TAG VARCHAR(500) NOT NULL
);
