CREATE TABLE IF NOT EXISTS CATGENOME.BLAST_LIST_SPECIES_TASK (
    TASK_ID         BIGINT NOT NULL PRIMARY KEY,
    DATABASE_ID     BIGINT NOT NULL,
    CREATED_DATE    TIMESTAMP NOT NULL,
    STATUS          INTEGER NOT NULL,
    STATUS_REASON   VARCHAR,
    UPDATE_DATE     TIMESTAMP,
    CONSTRAINT blast_list_species_task_database_id_fkey FOREIGN KEY (DATABASE_ID) REFERENCES CATGENOME.BLAST_DATABASE(DATABASE_ID)
);

CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_BLAST_DATABASE_ORGANISM START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS CATGENOME.BLAST_DATABASE_ORGANISM (
    DATABASE_ORGANISM_ID  BIGINT NOT NULL PRIMARY KEY,
    DATABASE_ID           BIGINT NOT NULL,
    TAX_ID                BIGINT NOT NULL,
    CONSTRAINT blast_database_id_fkey FOREIGN KEY (DATABASE_ID) REFERENCES CATGENOME.BLAST_DATABASE(DATABASE_ID)
);
