CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_PDB_FILE START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS CATGENOME.PDB_FILE (
    PDB_FILE_ID         BIGINT NOT NULL PRIMARY KEY,
    BIO_DATA_ITEM_ID    BIGINT NOT NULL,
    GENE_ID             VARCHAR NOT NULL,
    METADATA            VARCHAR
);
