CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_TASK START WITH 1 INCREMENT BY 1;
ALTER SEQUENCE CATGENOME.S_TASK RESTART WITH (SELECT MAX(TASK_ID) + 1 FROM CATGENOME.TASK);

ALTER TABLE CATGENOME.TASK ADD COLUMN BLAST_TASK_ID BIGINT;
UPDATE CATGENOME.TASK set BLAST_TASK_ID = TASK_ID;
ALTER TABLE CATGENOME.TASK ALTER COLUMN BLAST_TASK_ID SET NOT NULL;
