CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_HEATMAP START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_HEATMAP_VALUE START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS CATGENOME.HEATMAP (
    HEATMAP_ID             BIGINT NOT NULL PRIMARY KEY,
    NAME                   VARCHAR NOT NULL,
    PRETTY_NAME            VARCHAR NOT NULL,
    TYPE                   BIGINT NOT NULL,
    PATH                   VARCHAR NOT NULL,
    ROW_TREE_PATH          VARCHAR NOT NULL,
    COLUMN_TREE_PATH       VARCHAR NOT NULL,
    CELL_ANNOTATION_PATH   VARCHAR NOT NULL,
    LABEL_ANNOTATION_PATH  VARCHAR NOT NULL,
    ROW_COUNT              BIGINT NOT NULL,
    COLUMN_COUNT           BIGINT NOT NULL,
    MAX_CELL_VALUE         BIGINT NOT NULL,
    MIN_CELL_VALUE         BIGINT NOT NULL,
    CONTENT                BLOB,
    ANNOTATION             BLOB,
    TREE                   BLOB
);

CREATE TABLE IF NOT EXISTS CATGENOME.HEATMAP_VALUE (
    VALUE_ID       BIGINT NOT NULL PRIMARY KEY,
    HEATMAP_ID     BIGINT NOT NULL,
    HEATMAP_VALUE  VARCHAR NOT NULL,
    CONSTRAINT HEATMAP_ID_FKEY FOREIGN KEY (HEATMAP_ID) REFERENCES CATGENOME.HEATMAP (HEATMAP_ID)
);
