CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_ACTIVITY START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS CATGENOME.ACTIVITY (
    ID BIGINT NOT NULL PRIMARY KEY,
    UID        VARCHAR NOT NULL,
    ITEM_ID        BIGINT NOT NULL,
    ITEM_TYPE        BIGINT NOT NULL,
    ACTION_TYPE       VARCHAR NOT NULL,
    DATETIME TIMESTAMP NOT NULL,
    USERNAME       VARCHAR NOT NULL,
    FIELD       VARCHAR NOT NULL,
    OLD_VALUE       VARCHAR,
    NEW_VALUE       VARCHAR,
    CONSTRAINT activity_item_id_fkey FOREIGN KEY (ITEM_ID) REFERENCES CATGENOME.GENE_ITEM (GENE_ITEM_ID)
);
