-- fix parent_projects
ALTER TABLE CATGENOME.PROJECT ALTER COLUMN parent_id SET DATA TYPE BIGINT;

-- add gene_item_id to reference_genome_table
ALTER TABLE CATGENOME.REFERENCE_GENOME ADD COLUMN GENE_ITEM_ID BIGINT;
ALTER TABLE CATGENOME.REFERENCE_GENOME ADD CONSTRAINT reference_genome_gene_item_id_foreign_key FOREIGN KEY (GENE_ITEM_ID) REFERENCES catgenome.gene_item(GENE_ITEM_ID);