ALTER TABLE CATGENOME.BIOLOGICAL_DATA_ITEM DROP COLUMN CREATED_BY;
ALTER TABLE CATGENOME.PROJECT DROP COLUMN CREATED_BY;
ALTER TABLE CATGENOME.BOOKMARK DROP COLUMN CREATED_BY;
DROP INDEX CATGENOME.bookmark_created_by_idx;
DROP INDEX CATGENOME.project_created_by_idx;