UPDATE catgenome.BIOLOGICAL_DATA_ITEM
SET NAME = CONCAT(NAME, CONCAT ( ' ID ', BIO_DATA_ITEM_ID))
WHERE
  BIO_DATA_ITEM_ID NOT IN
  (
    SELECT MIN(BIO_DATA_ITEM_ID)
    FROM catgenome.BIOLOGICAL_DATA_ITEM
    GROUP BY NAME
    HAVING count(*) > 1
  ) AND
  BIO_DATA_ITEM_ID IN
  (
    SELECT G1.BIO_DATA_ITEM_ID
    FROM catgenome.BIOLOGICAL_DATA_ITEM AS G1
      INNER JOIN catgenome.BIOLOGICAL_DATA_ITEM AS G2
        ON G1.NAME = G2.NAME AND G1.BIO_DATA_ITEM_ID <> G2.BIO_DATA_ITEM_ID
  );

UPDATE catgenome.BIOLOGICAL_DATA_ITEM
SET NAME = CONCAT(NAME, CONCAT ( ' ID ', BIO_DATA_ITEM_ID))
WHERE
  BIO_DATA_ITEM_ID IN
  (
    SELECT BIO_DATA_ITEM_ID
    FROM catgenome.BIOLOGICAL_DATA_ITEM
    WHERE catgenome.BIOLOGICAL_DATA_ITEM.NAME = ''
  );

ALTER TABLE catgenome.BIOLOGICAL_DATA_ITEM ADD CONSTRAINT NAME_UNIQUE_CONST UNIQUE(NAME);
