CREATE TABLE IF NOT EXISTS CATGENOME.GENOME_ANNOTATION_DATA_ITEM (
    REFERENCE_GENOME_ID    BIGINT   NOT NULL,
    BIO_DATA_ITEM_ID       BIGINT   NOT NULL,
    CONSTRAINT ANNOTATION_BIO_DATA_ITEM_ID_FKEY FOREIGN KEY (BIO_DATA_ITEM_ID) REFERENCES CATGENOME.BIOLOGICAL_DATA_ITEM (BIO_DATA_ITEM_ID),
    CONSTRAINT ANNOTATION_REFERENCE_GENOME_ID_FKEY FOREIGN KEY (REFERENCE_GENOME_ID) REFERENCES CATGENOME.REFERENCE_GENOME (REFERENCE_GENOME_ID)
);
CREATE INDEX GENOME_ANNOTATION_IDX ON CATGENOME.GENOME_ANNOTATION_DATA_ITEM(REFERENCE_GENOME_ID);