CREATE TABLE IF NOT EXISTS CATGENOME.GENOME_SPECIES (
  SPECIES_NAME        VARCHAR(250)   NOT NULL,
  SPECIES_VERSION     VARCHAR(250)   NOT NULL,
  CONSTRAINT species_version_unique UNIQUE (species_version)
);
ALTER TABLE CATGENOME.REFERENCE_GENOME ADD COLUMN SPECIES_VERSION VARCHAR(250) NULL;
ALTER TABLE CATGENOME.REFERENCE_GENOME ADD CONSTRAINT SPECIES_VERSION_FKEY FOREIGN KEY (SPECIES_VERSION) REFERENCES CATGENOME.GENOME_SPECIES(SPECIES_VERSION) ON DELETE SET NULL;