ALTER TABLE CATGENOME.TASK ALTER COLUMN TITLE TEXT;
ALTER TABLE CATGENOME.TASK ALTER COLUMN STATUS_REASON TEXT;
ALTER TABLE CATGENOME.TASK ALTER COLUMN QUERY TEXT;
ALTER TABLE CATGENOME.TASK ALTER COLUMN DATABASE TEXT;
ALTER TABLE CATGENOME.TASK ALTER COLUMN OPTIONS TEXT;