CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_BAM_COVERAGE START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS CATGENOME.BAM_COVERAGE (
    COVERAGE_ID     BIGINT NOT NULL PRIMARY KEY,
    BAM_ID          BIGINT NOT NULL,
    STEP            INTEGER NOT NULL,
    COVERAGE        NUMERIC NOT NULL,
    CONSTRAINT cv_bam_id_fkey FOREIGN KEY (BAM_ID) REFERENCES CATGENOME.BAM (BAM_ID)
);
