CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_HEATMAP START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS CATGENOME.HEATMAP (
    HEATMAP_ID             BIGINT NOT NULL PRIMARY KEY,
    BIO_DATA_ITEM_ID       BIGINT NOT NULL,
    ROW_TREE_PATH          VARCHAR,
    COLUMN_TREE_PATH       VARCHAR,
    CELL_ANNOTATION_PATH   VARCHAR,
    LABEL_ANNOTATION_PATH  VARCHAR,
    CELL_VALUE_TYPE        INTEGER NOT NULL,
    MAX_CELL_VALUE         DECIMAL,
    MIN_CELL_VALUE         DECIMAL,
    CELL_VALUES            bytea,
    COLUMN_LABELS          bytea,
    ROW_LABELS             bytea,
    CONTENT                bytea,
    CELL_ANNOTATION        bytea,
    LABEL_ANNOTATION       bytea,
    ROW_TREE               bytea,
    COLUMN_TREE            bytea,
    CONSTRAINT hmp_biological_data_item_id_fkey FOREIGN KEY (BIO_DATA_ITEM_ID) REFERENCES CATGENOME.BIOLOGICAL_DATA_ITEM (BIO_DATA_ITEM_ID)
);
