ALTER TABLE CATGENOME.PROJECT DROP COLUMN IF EXISTS description;

CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_PROJECT_DESCRIPTION START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS CATGENOME.PROJECT_DESCRIPTION (
    ID                     BIGINT NOT NULL PRIMARY KEY,
    PROJECT_ID             BIGINT NOT NULL,
    NAME                   VARCHAR NOT NULL,
    CONTENT                BYTEA NOT NULL,
    CONSTRAINT project_description_unique UNIQUE (PROJECT_ID, NAME),
    CONSTRAINT project_description_project_id_fkey FOREIGN KEY (PROJECT_ID) REFERENCES CATGENOME.PROJECT (PROJECT_ID)
);
