CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_LINEAGE_TREE START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS CATGENOME.LINEAGE_TREE (
    LINEAGE_TREE_ID     BIGINT NOT NULL PRIMARY KEY,
    BIO_DATA_ITEM_ID    BIGINT NOT NULL,
    DESCRIPTION         VARCHAR,
    NODES_PATH          VARCHAR NOT NULL,
    EDGES_PATH          VARCHAR,
    CONSTRAINT lng_biological_data_item_id_fkey FOREIGN KEY (BIO_DATA_ITEM_ID) REFERENCES CATGENOME.BIOLOGICAL_DATA_ITEM (BIO_DATA_ITEM_ID)
);

CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_LINEAGE_TREE_NODE START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS CATGENOME.LINEAGE_TREE_NODE (
    LINEAGE_TREE_NODE_ID BIGINT NOT NULL PRIMARY KEY,
    LINEAGE_TREE_ID      BIGINT NOT NULL,
    NAME                 VARCHAR NOT NULL,
    DESCRIPTION          VARCHAR,
    REFERENCE_ID         BIGINT,
    CREATION_DATE        TIMESTAMP,
    ATTRIBUTES           VARCHAR,
    CONSTRAINT node_lineage_tree_id_fkey FOREIGN KEY (LINEAGE_TREE_ID) REFERENCES CATGENOME.LINEAGE_TREE(LINEAGE_TREE_ID)
);

CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_LINEAGE_TREE_EDGE START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS CATGENOME.LINEAGE_TREE_EDGE (
    LINEAGE_TREE_EDGE_ID BIGINT NOT NULL PRIMARY KEY,
    LINEAGE_TREE_ID      BIGINT NOT NULL,
    ATTRIBUTES           VARCHAR,
    TYPE_OF_INTERACTION  VARCHAR,
    NODE_FROM            BIGINT NOT NULL,
    NODE_TO              BIGINT NOT NULL,
    CONSTRAINT edge_lineage_tree_id_fkey FOREIGN KEY (LINEAGE_TREE_ID) REFERENCES CATGENOME.LINEAGE_TREE(LINEAGE_TREE_ID)
);
