CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_PATHWAY_ORGANISM START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS CATGENOME.PATHWAY_ORGANISM (
    PATHWAY_ORGANISM_ID    BIGINT NOT NULL PRIMARY KEY,
    PATHWAY_ID             BIGINT NOT NULL,
    TAX_ID                 BIGINT NOT NULL,
    CONSTRAINT po_pathway_id_fkey FOREIGN KEY (PATHWAY_ID) REFERENCES CATGENOME.PATHWAY (PATHWAY_ID)
);
