CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_TASK START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS CATGENOME.TASK_NEW (
    TASK_ID         BIGINT NOT NULL PRIMARY KEY,
    BLAST_TASK_ID   BIGINT NOT NULL,
    TITLE           VARCHAR(250),
    CREATED_DATE    TIMESTAMP NOT NULL,
    STATUS          INTEGER NOT NULL,
    END_DATE        TIMESTAMP,
    STATUS_REASON   VARCHAR(250),
    QUERY           VARCHAR(250),
    DATABASE_ID     VARCHAR(250),
    EXECUTABLE      VARCHAR(250),
    ALGORITHM       VARCHAR(250),
    OPTIONS         VARCHAR(250),
    OWNER           VARCHAR(250)
);
INSERT INTO CATGENOME.TASK_NEW
SELECT  CATGENOME.S_TASK.nextval,
        TASK_ID,
        TITLE,
        CREATED_DATE,
        STATUS,
        END_DATE,
        STATUS_REASON,
        QUERY,
        DATABASE_ID,
        EXECUTABLE,
        ALGORITHM,
        OPTIONS,
        OWNER
FROM CATGENOME.TASK;

CREATE TABLE IF NOT EXISTS CATGENOME.TASK_PARAMETER_NEW (
    PARAMETER_ID    BIGINT NOT NULL PRIMARY KEY,
    TASK_ID         BIGINT NOT NULL,
    PARAMETER       VARCHAR(250) NOT NULL,
    VALUE           VARCHAR(250) NOT NULL,
    CONSTRAINT parameter_task_id1_fkey FOREIGN KEY (TASK_ID) REFERENCES CATGENOME.TASK_NEW(TASK_ID)
);
INSERT INTO CATGENOME.TASK_PARAMETER_NEW (PARAMETER_ID, TASK_ID, PARAMETER, VALUE)
SELECT  p.PARAMETER_ID,
        (select t.task_id from CATGENOME.TASK_NEW t where t.BLAST_TASK_ID = p.task_id),
        p.PARAMETER,
        p.VALUE
FROM CATGENOME.TASK_PARAMETER p;

CREATE TABLE IF NOT EXISTS CATGENOME.TASK_ORGANISM_NEW (
    ORGANISM_ID     BIGINT NOT NULL PRIMARY KEY,
    TASK_ID         BIGINT NOT NULL,
    ORGANISM        BIGINT NOT NULL,
    CONSTRAINT organism_task_id1_fkey FOREIGN KEY (TASK_ID) REFERENCES CATGENOME.TASK_NEW(TASK_ID)
);
INSERT INTO CATGENOME.TASK_ORGANISM_NEW (ORGANISM_ID, TASK_ID, ORGANISM)
SELECT  o.ORGANISM_ID,
        (select t.task_id from CATGENOME.TASK_NEW t where t.BLAST_TASK_ID = o.task_id),
        o.ORGANISM
FROM CATGENOME.TASK_ORGANISM o;


CREATE TABLE IF NOT EXISTS CATGENOME.TASK_EXCL_ORGANISM_NEW (
    ORGANISM_ID     BIGINT NOT NULL PRIMARY KEY,
    TASK_ID         BIGINT NOT NULL,
    ORGANISM        BIGINT NOT NULL,
    CONSTRAINT excl_organism_task_id1_fkey FOREIGN KEY (TASK_ID) REFERENCES CATGENOME.TASK_NEW(TASK_ID)
);
INSERT INTO CATGENOME.TASK_EXCL_ORGANISM_NEW (ORGANISM_ID, TASK_ID, ORGANISM)
SELECT  o.ORGANISM_ID,
        (select t.task_id from CATGENOME.TASK_NEW t where t.BLAST_TASK_ID = o.task_id),
        o.ORGANISM
FROM CATGENOME.TASK_EXCL_ORGANISM o;


drop table CATGENOME.TASK;
drop table CATGENOME.TASK_PARAMETER;
drop table CATGENOME.TASK_ORGANISM;
drop table CATGENOME.TASK_EXCL_ORGANISM;


ALTER TABLE CATGENOME.TASK_NEW RENAME TO CATGENOME.TASK;
ALTER TABLE CATGENOME.TASK_PARAMETER_NEW RENAME TO CATGENOME.TASK_PARAMETER;
ALTER TABLE CATGENOME.TASK_ORGANISM_NEW RENAME TO CATGENOME.TASK_ORGANISM;
ALTER TABLE CATGENOME.TASK_EXCL_ORGANISM_NEW RENAME TO CATGENOME.TASK_EXCL_ORGANISM;