ALTER TABLE CATGENOME.TASK ALTER COLUMN TITLE TYPE TEXT;
ALTER TABLE CATGENOME.TASK ALTER COLUMN STATUS_REASON TYPE TEXT;
ALTER TABLE CATGENOME.TASK ALTER COLUMN QUERY TYPE TEXT;
ALTER TABLE CATGENOME.TASK ALTER COLUMN DATABASE TYPE TEXT;
ALTER TABLE CATGENOME.TASK ALTER COLUMN OPTIONS TYPE TEXT;
