CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_HOMOLOG_GENE_DESC START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS CATGENOME.HOMOLOG_GENE_DESC (
    ID BIGINT NOT NULL PRIMARY KEY,
    SYMBOL VARCHAR(500) NOT NULL,
    TITLE VARCHAR(500) NOT NULL,
    TAX_ID BIGINT NOT NULL,
    PROT_GI BIGINT,
    PROT_ACC VARCHAR(500),
    PROT_LEN BIGINT,
    NUC_GI BIGINT,
    NUC_ACC VARCHAR(500),
    LOCUS_TAG VARCHAR(500)
);
