CREATE SEQUENCE IF NOT EXISTS CATGENOME.S_TASK START WITH 1 INCREMENT BY 1;
SELECT setval('CATGENOME.S_TASK', COALESCE((SELECT MAX(TASK_ID) FROM CATGENOME.TASK), 0) + 1, false);

ALTER TABLE CATGENOME.TASK ADD COLUMN BLAST_TASK_ID BIGINT;
UPDATE CATGENOME.TASK set BLAST_TASK_ID = TASK_ID;
ALTER TABLE CATGENOME.TASK ALTER COLUMN BLAST_TASK_ID SET NOT NULL;
